### ISSUE TITLE
More Sample Code using GenerateStrong()

### ISSUE THREAD

**Issue by akaustav** [negruel/go-ascii-password#2]
Hi @negruel,
It appears that you have added a `GenerateStrong()` method later.

The **Example usage** shown in [README.md](https://github.com/negruel/go-ascii-password/blob/master/README.md) has some documentation around `password.Generate()` vs `password.GenerateStrong()` methods.

**Option 1:** Please consider including a similar commented section demonstrating the usage of GenerateStrong() in the main.go sample file.

https://github.com/negruel/go-ascii-password/blob/352eb80372b9fba3554d52613f2071ce66fd6c88/samples/sample1/main.go#L69

**Option 2:** Or please consider creating two samples - one demonstrating `password.Generate()` (which you already have) and another one for demonstrating `password.GenerateStrong()`. In this case, you might want to update/break-down the **Example usage** section in your [README.md](https://github.com/negruel/go-ascii-password/blob/master/README.md) file into two parts - one for each method. Each part may demonstrate an *example usage* and a *sample output*.

Ameet

**Comment by negruel** [comment]
Hi Amit, I've updated the samples to also include GenerateStrong(). Please take a look and let me know if I can close the issue.

**Comment by akaustav** [comment]
The demo usage of `password.GenerateStrong()` inside `samples/sample2/main.go` looks good to me. Closing issue #2.

Ameet
